// Types
import type { ApplicationFormData } from "@/app/(dashboard)/portal/applications/new/_types";

export const initialFormData: ApplicationFormData = {
  organization: "",
  service: "",
  comments: "",
  marriage_details: {
    date_of_marriage: "",
    husband_name: "",
    husband_id_passport: "",
    husband_age: "",
    husband_marital_status: "First Marriage",
    husband_occupation: "",
    husband_residence_county: "",
    husband_residence_sub_county: "",
    wife_name: "",
    wife_id_passport: "",
    wife_age: "",
    wife_marital_status: "Virgin",
    wife_occupation: "",
    wife_residence_county: "",
    wife_residence_sub_county: "",
    wife_waliyy_name: "",
    wife_waliyy_relationship: "",
    agreed_mahr: "",
    paid_mahr_and_deferred: "",
    particulars_of_gifts: "",
    place_of_marriage: "",
    county_of_marriage: "",
    witness_1_name: "",
    witness_1_id: "",
    witness_2_name: "",
    witness_2_id: "",
  },
  pilgrim_details: {
    full_name: "",
    passport_number: "",
    nationality: "",
    date_of_birth: "",
    gender: "Male",
    trip_type: "Hajj",
    expected_travel_date: "",
    travel_agent_name: "",
    guidance_requested: false,
  },
  education_details: {
    full_name: "",
    passport_number: "",
    institution_name: "",
    course_of_study: "",
    country: "",
    scholarship_details: "",
  },
  travel_visa_details: {
    full_name: "",
    passport_number: "",
    destination_country: "",
    trip_purpose: "Religious",
    expected_travel_date: "",
  },
  employment_details: {
    full_name: "",
    id_number: "",
    position_applied_for: "",
    employer_name: "",
  },
};
