import { SocialPost } from "./types";

export const OFFICIAL_CHANNELS = {
  x: {
    name: "X (Twitter)",
    handle: "@SUPKEM1",
    url: "https://x.com/SUPKEM1",
    color: "#000000",
    bgClass: "bg-slate-900 text-white hover:bg-black",
    badgeClass: "bg-slate-900 text-white border-slate-700",
  },
  facebook: {
    name: "Facebook",
    handle: "Supreme Council of Kenya Muslims",
    url: "https://www.facebook.com/p/Supreme-Council-of-Kenya-Muslims-100079747610399/",
    color: "#1877F2",
    bgClass: "bg-[#1877F2] text-white hover:bg-[#166fe5]",
    badgeClass: "bg-[#1877F2]/15 text-[#1877F2] border-[#1877F2]/30",
  },
  instagram: {
    name: "Instagram",
    handle: "@supkem_kenya",
    url: "https://www.instagram.com/supkem_kenya/",
    color: "#E1306C",
    bgClass: "bg-gradient-to-tr from-[#f09433] via-[#dc2743] to-[#bc1888] text-white",
    badgeClass: "bg-pink-500/15 text-pink-600 border-pink-500/30",
  },
  tiktok: {
    name: "TikTok",
    handle: "@supkem_kenya",
    url: "https://www.tiktok.com/@supkem_kenya",
    color: "#000000",
    bgClass: "bg-black text-white hover:bg-neutral-800",
    badgeClass: "bg-cyan-500/15 text-cyan-600 border-cyan-500/30",
  },
};

export const INITIAL_SOCIAL_POSTS: SocialPost[] = [
  {
    id: "post-1",
    platform: "x",
    author: {
      name: "SUPKEM Official",
      handle: "@SUPKEM1",
      avatar: "/logo.png",
      profileUrl: "https://x.com/SUPKEM1",
      isVerified: true,
    },
    content:
      "🔴 PRESS BRIEFING: SUPKEM National Executive Council convenes strategic consultations in Nairobi on the 2026/1447H Hajj pilgrimage readiness, regulatory protocols for travel agencies, and enhanced community welfare initiatives across all 47 counties. #SUPKEM #Hajj2026 #KenyaMuslims #CommunityDevelopment",
    publishedAt: "2026-03-08T09:30:00Z",
    relativeTime: "2 hours ago",
    mediaType: "image",
    images: ["/images/slider/olesaudib.jpg"],
    likes: 342,
    shares: 89,
    comments: 24,
    postUrl: "https://x.com/SUPKEM1",
    tags: ["SUPKEM", "Hajj2026", "KenyaMuslims", "CommunityDevelopment"],
    isPinned: true,
  },
  {
    id: "post-2",
    platform: "facebook",
    author: {
      name: "Supreme Council of Kenya Muslims",
      handle: "Supreme Council of Kenya Muslims",
      avatar: "/logo.png",
      profileUrl: "https://www.facebook.com/p/Supreme-Council-of-Kenya-Muslims-100079747610399/",
      isVerified: true,
    },
    content:
      "Strengthening institutional bridges: SUPKEM leadership held fruitful interfaith consultations with religious leaders and civil society organizations in Nairobi. The discussions centered on peace consolidation, national cohesion, and joint humanitarian outreach in drought-affected and vulnerable communities. Read more on our ongoing collaborative efforts. #InterfaithDialogue #SUPKEMKenya #PeaceBuilding #NationalUnity",
    publishedAt: "2026-03-07T16:15:00Z",
    relativeTime: "Yesterday",
    mediaType: "gallery",
    images: [
      "/images/slider/ole_olesapitb.jpg",
      "/images/slider/olerezo_nb.jpg",
      "/images/slide31602.jpg",
    ],
    likes: 854,
    shares: 198,
    comments: 67,
    postUrl: "https://www.facebook.com/p/Supreme-Council-of-Kenya-Muslims-100079747610399/",
    tags: ["InterfaithDialogue", "SUPKEMKenya", "PeaceBuilding", "NationalUnity"],
  },
  {
    id: "post-3",
    platform: "instagram",
    author: {
      name: "SUPKEM Kenya",
      handle: "@supkem_kenya",
      avatar: "/logo.png",
      profileUrl: "https://www.instagram.com/supkem_kenya/",
      isVerified: true,
    },
    content:
      "✨ Inspiring the future generation: Highlights from the Regional Youth & Madrasa Digitization Summit hosted at SUPKEM Islamic Centre. Equipping young Muslims with digital skills, scholarship opportunities, and leadership capacity to thrive in a global economy. 📸 Swipe through our official photo moments! #SUPKEMYouth #EducationForEmpowerment #DigitalMadrasa #UmmahRising #Kenya",
    publishedAt: "2026-03-06T11:45:00Z",
    relativeTime: "2 days ago",
    mediaType: "gallery",
    images: [
      "/images/slider/image.png",
      "/images/slider/oledarknb.jpg",
    ],
    likes: 1208,
    shares: 312,
    comments: 92,
    postUrl: "https://www.instagram.com/supkem_kenya/",
    tags: ["SUPKEMYouth", "EducationForEmpowerment", "DigitalMadrasa", "UmmahRising", "Kenya"],
  },
  {
    id: "post-5",
    platform: "x",
    author: {
      name: "SUPKEM Official",
      handle: "@SUPKEM1",
      avatar: "/logo.png",
      profileUrl: "https://x.com/SUPKEM1",
      isVerified: true,
    },
    content:
      "📢 NOTICE TO APPLICANTS: Registration and verification for SUPKEM International Study Abroad Support Letters is currently active on our official digital portal. Visit supkem.org/services to submit credentials online. #SUPKEMServices #StudyAbroad #EducationSupport",
    publishedAt: "2026-03-04T10:20:00Z",
    relativeTime: "4 days ago",
    mediaType: "text",
    likes: 215,
    shares: 74,
    comments: 18,
    postUrl: "https://x.com/SUPKEM1",
    tags: ["SUPKEMServices", "StudyAbroad", "EducationSupport"],
  },
  {
    id: "post-6",
    platform: "tiktok",
    author: {
      name: "SUPKEM Kenya",
      handle: "@supkem_kenya",
      avatar: "/logo.png",
      profileUrl: "https://www.tiktok.com/@supkem_kenya",
      isVerified: true,
    },
    content:
      "Behind the scenes with our volunteer disaster response team delivering emergency relief packages to families in Garissa and Wajir. Every share helps spread awareness! 🤲💚 #SUPKEMCare #HumanitarianAid #KenyaMuslims #TikTokKenya",
    publishedAt: "2026-03-03T18:30:00Z",
    relativeTime: "5 days ago",
    mediaType: "video",
    videoThumbnail: "/images/slide31602.jpg",
    videoDuration: "0:58",
    likes: 3820,
    shares: 940,
    comments: 210,
    postUrl: "https://www.tiktok.com/@supkem_kenya",
    tags: ["SUPKEMCare", "HumanitarianAid", "KenyaMuslims", "TikTokKenya"],
  },
];
